apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora
  labels:
    app: calculadora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculadora
  template:
    metadata:
      labels:
        app: calculadora
    spec:
      containers:
      - name: calculadora
        image: crisdockerz/calculadora-api:5  # ðŸ”„ Altere para seu Docker Hub
        ports:
        - containerPort: 8000

